name: Salle
favicon: null
layout_spectrum: 0.18052692292258143
typography_spectrum: 0.74022
title: "\"Use a picture. It's worth a thousand words.\""
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f5f8e'
    - '#fffffd'
    - '#7a8dab'
    - '#2d2c27'
    - '#d7d8dc'
  brandStrength: 0
  lightness: 0.793907706392929
  saturation: 0.08880953001789749
  rhythmicContrast: 0.25
purpose: []
